### ISSUE TITLE
0.5.0 - Gamepad disconnect

### ISSUE THREAD

**Issue by pabermod** [dancol90/mi-360#18] opened 2020-04-23 14:56 UTC
Using the installer the gamepad connects, and then disconnects

**Comment by dancol90** [comment] 2020-04-23 22:08
Stating the it just does not work doesn't help me. I need more information.

Anyway, try turning the Bluetooth of your PC off and then on again, then reconnect your gamepad. What happends?

**Comment by pabermod** [comment] 2020-04-24 13:45
Sorry, what I meant is I get a windows notification saying a gamepad was connected, and a second later I get a notification saying a gamepad was disconnected.

Same problem after turning off an on bluetooth

**Comment by D3rSchurk3** [comment] 2020-05-11 16:06
Same here. Are you already working on a fix? Thx.

**Comment by dancol90** [comment] 2020-05-31 16:36
Hi everybody, sorry for the wait!

Please update to the newly released mi-360 v0.5.1, as now it logs its operation to file, so you can collect useful information to send here for me to invesitgate your issues!

I ask you to follow these steps:
- Update to v0.5.1
- Run mi-360 and use it normally. Try to reproduce the issues above.
- Navigate to `C:\Users\<username>\AppData\Local\Temp\` (enter `%TEMP%` in Explorer address bar)
- Search the most recente file named `mi-360-<date>.log`  and upload it or its content here

**Comment by FFrelay** [comment] 2020-06-03 13:17
> 
> 
> Hi everybody, sorry for the wait!
> 
> Please update to the newly released mi-360 v0.5.1, as now it logs its operation to file, so you can collect useful information to send here for me to invesitgate your issues!
> 
> I ask you to follow these steps:
> 
>     * Update to v0.5.1
> 
>     * Run mi-360 and use it normally. Try to reproduce the issues above.
> 
>     * Navigate to `C:\Users\<username>\AppData\Local\Temp\` (enter `%TEMP%` in Explorer address bar)
> 
>     * Search the most recente file named `mi-360-<date>.log`  and upload it or its content here

Hi, here is my log, pls take a look. 

> [20:14:12 INF][mi360.Mi360Application] Initializing resources
[20:14:14 INF][mi360.XInputManager] Initializing ViGEm client
[20:14:14 INF][mi360.Win32.HidMonitor] Initializing HID device monitor with filter VID&00022717_PID&3144
[20:14:14 INF][mi360.Win32.HidMonitor] Start monitoring for filter VID&00022717_PID&3144
[20:14:14 INF][mi360.Mi360Application] mi-360 is running
[20:14:19 INF][mi360.Win32.HidMonitor] Detected attached HID devices matching filter VID&00022717_PID&3144
[20:14:19 INF][mi360.Mi360Application] New HID device connected: \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.XInputManager] Adding device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.MiGamepad] Initializing MiGamepad handler for device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.XInputManager] Starting \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.MiGamepad] Starting worker thread for VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.MiGamepad] Disabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.MiGamepad] Enabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.MiGamepad] Opening HID device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.MiGamepad] Connecting to ViGEm client
[20:14:19 INF][mi360.MiGamepad] Disconnecting ViGEm client
[20:14:19 INF][mi360.Mi360Application] XInput gamepad connected
[20:14:19 INF][mi360.MiGamepad] Closing HID device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.MiGamepad] Disabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 DBG][mi360.Mi360Application] Notifying user: Gamepad connected - A new gamepad is now available as XInput device.
[20:14:19 INF][mi360.MiGamepad] Enabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.MiGamepad] Exiting worker thread for VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.XInputManager] Stopping device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.XInputManager] Deinitializing and removing device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.MiGamepad] Deinitializing MiGamepad handler for device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&38dc73c&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[20:14:19 INF][mi360.Mi360Application] XInput gamepad disconnected
[20:14:19 DBG][mi360.Mi360Application] Notifying user: Gamepad disconnected - A gamepad has disconnected and is not available anymore.
[20:15:44 INF][mi360.Mi360Application] Exiting
[20:15:44 INF][mi360.Mi360Application] Deinitializing resources
[20:15:44 INF][mi360.Win32.HidMonitor] Stop monitoring for filter VID&00022717_PID&3144
[20:15:44 INF][mi360.Win32.HidMonitor] Deinitilizing HID monitor for VID&00022717_PID&3144
[20:15:44 INF][mi360.XInputManager] Cleaning up running gamepads
[20:15:44 INF][mi360.XInputManager] Deinitializing ViGEm client

**Comment by iljadvm** [comment] 2020-06-05 20:40
Hello, Daniel!
Here is mine. I have two game-pads:

[23:31:16 INF][mi360.Mi360Application] Initializing resources
[23:31:16 INF][mi360.XInputManager] Initializing ViGEm client
[23:31:16 INF][mi360.Win32.HidMonitor] Initializing HID device monitor with filter VID&00022717_PID&3144
[23:31:16 INF][mi360.Win32.HidMonitor] Start monitoring for filter VID&00022717_PID&3144
[23:31:16 INF][mi360.Mi360Application] mi-360 is running
[23:31:16 INF][mi360.Win32.HidMonitor] Detected attached HID devices matching filter VID&00022717_PID&3144
[23:31:16 INF][mi360.Mi360Application] New HID device connected: \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.XInputManager] Adding device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Initializing MiGamepad handler for device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.XInputManager] Starting \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.Win32.HidMonitor] Detected attached HID devices matching filter VID&00022717_PID&3144
[23:31:16 INF][mi360.Mi360Application] New HID device connected: \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.XInputManager] Adding device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Initializing MiGamepad handler for device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.XInputManager] Starting \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Starting worker thread for VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Starting worker thread for VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Disabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Disabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Enabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Enabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Opening HID device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Opening HID device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Connecting to ViGEm client
[23:31:16 INF][mi360.MiGamepad] Connecting to ViGEm client
[23:31:16 INF][mi360.MiGamepad] Disconnecting ViGEm client
[23:31:16 INF][mi360.Mi360Application] XInput gamepad connected
[23:31:16 DBG][mi360.Mi360Application] Notifying user: Gamepad connected - A new gamepad is now available as XInput device.
[23:31:16 INF][mi360.MiGamepad] Closing HID device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Disabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Enabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Exiting worker thread for VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.XInputManager] Stopping device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.XInputManager] Deinitializing and removing device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Deinitializing MiGamepad handler for device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.Mi360Application] XInput gamepad disconnected
[23:31:16 DBG][mi360.Mi360Application] Notifying user: Gamepad disconnected - A gamepad has disconnected and is not available anymore.
[23:31:16 INF][mi360.MiGamepad] Disconnecting ViGEm client
[23:31:16 INF][mi360.MiGamepad] Closing HID device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Disabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Enabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Exiting worker thread for VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.Mi360Application] XInput gamepad connected
[23:31:16 DBG][mi360.Mi360Application] Notifying user: Gamepad connected - A new gamepad is now available as XInput device.
[23:31:16 INF][mi360.XInputManager] Stopping device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.XInputManager] Deinitializing and removing device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.MiGamepad] Deinitializing MiGamepad handler for device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:16 INF][mi360.Mi360Application] XInput gamepad disconnected
[23:31:16 DBG][mi360.Mi360Application] Notifying user: Gamepad disconnected - A gamepad has disconnected and is not available anymore.
[23:31:21 INF][mi360.Win32.HidMonitor] Detected removed HID devices matching filter VID&00022717_PID&3144
[23:31:21 INF][mi360.Mi360Application] HID device disconnected: \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:21 WRN][mi360.XInputManager] Requested removal of non-existing device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:21 INF][mi360.Win32.HidMonitor] Detected removed HID devices matching filter VID&00022717_PID&3144
[23:31:21 INF][mi360.Mi360Application] HID device disconnected: \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:21 WRN][mi360.XInputManager] Requested removal of non-existing device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.Win32.HidMonitor] Detected attached HID devices matching filter VID&00022717_PID&3144
[23:31:41 INF][mi360.Mi360Application] New HID device connected: \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.XInputManager] Adding device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.MiGamepad] Initializing MiGamepad handler for device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.XInputManager] Starting \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.MiGamepad] Starting worker thread for VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.MiGamepad] Disabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.MiGamepad] Enabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.MiGamepad] Opening HID device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.MiGamepad] Connecting to ViGEm client
[23:31:41 INF][mi360.MiGamepad] Disconnecting ViGEm client
[23:31:41 INF][mi360.Mi360Application] XInput gamepad connected
[23:31:41 DBG][mi360.Mi360Application] Notifying user: Gamepad connected - A new gamepad is now available as XInput device.
[23:31:41 INF][mi360.MiGamepad] Closing HID device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.MiGamepad] Disabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.MiGamepad] Enabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.MiGamepad] Exiting worker thread for VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.XInputManager] Stopping device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.XInputManager] Deinitializing and removing device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.MiGamepad] Deinitializing MiGamepad handler for device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&45be63&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:41 INF][mi360.Mi360Application] XInput gamepad disconnected
[23:31:41 DBG][mi360.Mi360Application] Notifying user: Gamepad disconnected - A gamepad has disconnected and is not available anymore.
[23:31:56 INF][mi360.Win32.HidMonitor] Detected attached HID devices matching filter VID&00022717_PID&3144
[23:31:56 INF][mi360.Mi360Application] New HID device connected: \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.XInputManager] Adding device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.MiGamepad] Initializing MiGamepad handler for device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.XInputManager] Starting \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.MiGamepad] Starting worker thread for VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.MiGamepad] Disabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.MiGamepad] Enabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.MiGamepad] Opening HID device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.MiGamepad] Connecting to ViGEm client
[23:31:56 INF][mi360.MiGamepad] Disconnecting ViGEm client
[23:31:56 INF][mi360.Mi360Application] XInput gamepad connected
[23:31:56 INF][mi360.MiGamepad] Closing HID device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 DBG][mi360.Mi360Application] Notifying user: Gamepad connected - A new gamepad is now available as XInput device.
[23:31:56 INF][mi360.MiGamepad] Disabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.MiGamepad] Enabling gamepad VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.MiGamepad] Exiting worker thread for VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.XInputManager] Stopping device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.XInputManager] Deinitializing and removing device \\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.MiGamepad] Deinitializing MiGamepad handler for device VendorID=0x2717, ProductID=0x3144, Version=0, DevicePath=\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&00022717_pid&3144#9&3924ab5f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
[23:31:56 INF][mi360.Mi360Application] XInput gamepad disconnected
[23:31:56 DBG][mi360.Mi360Application] Notifying user: Gamepad disconnected - A gamepad has disconnected and is not available anymore.
[23:32:59 INF][mi360.Mi360Application] Exiting
[23:32:59 INF][mi360.Mi360Application] Deinitializing resources
[23:32:59 INF][mi360.Win32.HidMonitor] Stop monitoring for filter VID&00022717_PID&3144
[23:32:59 INF][mi360.Win32.HidMonitor] Deinitilizing HID monitor for VID&00022717_PID&3144
[23:32:59 INF][mi360.XInputManager] Cleaning up running gamepads
[23:32:59 INF][mi360.XInputManager] Deinitializing ViGEm client

**Comment by dancol90** [comment] 2020-06-07 13:31
It seems like the problem is related to the impossibility to gain an exclusive access to the HID device. I thought that disabling and renabling the device, as someone suggested, would solve the problem once for all. Actually, in my test machine this approach was successfull, but apparently it's not enough in some cases.

@iljadvm, @ondvpoh, @pabermod, @D3rSchurk3, can I ask you which version and build of Windows are you using (e.g. I'm on Windows 10 version 1909 build 18363.863)

**Comment by pabermod** [comment] 2020-06-07 13:33
I'm using same windows build as you @dancol90

**Comment by FFrelay** [comment] 2020-06-07 15:35
Mine is Windows 10 2004 build 19041.264, I also had the same problem when I used Windows 10 1909.

**Comment by dancol90** [comment] 2020-06-07 17:17
v0.5.2 has just been release here: https://github.com/dancol90/mi-360/releases/tag/v0.5.2

It now should be able to run even if it fails to hide the Xiaomi Gamepad from other applications. It may cause incompatibilities with some games, but for now there's no better solution, as Windows 10 prevents exclusive access to HID devices more often than I immagined.

**Closed as completed by dancol90** 2020-06-07 17:17 UTC
